package com.paymentMicroservice.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.util.UUID;

@Data
@Schema(name = "StripeSepaTokenDTO", description = "DTO containing details for Stripe SEPA token generation.")
public class StripeSepaTokenDTO {

    @Schema(description = "Correlation ID to track the request",
            example = "123e4567-e89b-12d3-a456-426614174000",
            nullable = true)
    private UUID correlationId;

    @NotNull
    @Schema(description = "IBAN (International Bank Account Number) associated with the SEPA account",
            example = "DE89370400440532013000",
            required = true)
    private String iban;

    @NotNull
    @Schema(description = "Name of the account holder for the SEPA account",
            example = "John Doe",
            required = true)
    private String accountHolderName;

    @NotNull
    @Schema(description = "Type of the account holder (e.g., individual or company)",
            example = "individual",
            required = true)
    private String accountHolderType;

    @Schema(description = "Indicates whether the SEPA tokenization was successful",
            example = "true",
            nullable = true)
    private boolean success;

    @Schema(description = "Token generated by Stripe after successful SEPA account processing",
            example = "sepa_tok_visa",
            nullable = true)
    private String token;
}