/**
 * Response object containing details of the created payment
 */
export interface CreatePaymentResponseDto {

  /**
   * Unique correlation ID for tracking the payment request
   */
  correlationId: string;

  /**
   * Unique identifier for the payment intent generated by the payment gateway
   */
  paymentIntentId: string;
}
