import { MovementDto } from '../models/movement-dto';

/**
 * DTO representing an invoice, including details such as the date of emission, description, associated movement, and file data.
 */
export type InvoiceDto = {

/**
 * Unique correlation ID to trace and associate requests/responses.
 */
'correlationId': string;

/**
 * Unique identifier for the entity, typically assigned upon creation or retrieval.
 */
'id': string;

/**
 * Version number for optimistic locking and concurrent updates management.
 */
'version': number;

/**
 * The date when the invoice was emitted.
 */
'dateOfEmission': string;

/**
 * A brief description of the invoice.
 */
'description': string;

/**
 * UUID of the associated movement, if any.
 */
'movementId'?: string | null;

/**
 * The file content of the invoice, stored as a byte array.
 */
'file'?: Array<string | null>;
'movement'?: MovementDto;

/**
 * The URL to the receipt generated by Stripe for the transaction
 */
'stripeReceiptUrl'?: string | null;

/**
 * The unique document number associated with the payment movement
 */
'movementDocumentNumber'?: string | null;

/**
 * The key for accessing the invoice file stored in S3. This is used to retrieve or delete the file associated with the invoice.
 */
'fileKey'?: string | null;

/**
 * Base64 encoded content of the invoice file (e.g., PDF), included in the response to display the file.
 */
'fileBase64'?: string | null;
};
