/**
 * DTO containing details for Stripe card token generation.
 */
export interface StripeCardTokenDto {

  /**
   * Card number (no spaces or dashes)
   */
  cardNumber: string;

  /**
   * Correlation ID to track the request
   */
  correlationId?: string | null;

  /**
   * CVC (Card Verification Code) of the card
   */
  cvc: string;

  /**
   * Email associated with the card
   */
  email: string;

  /**
   * Expiration month of the card
   */
  expMonth: string;

  /**
   * Expiration year of the card
   */
  expYear: string;

  /**
   * Indicates whether the card tokenization was successful
   */
  success?: boolean | null;

  /**
   * Token generated by Stripe after successful card processing
   */
  token?: string | null;
}
