package com.portalMicroservice.dto.payment;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;

import java.util.UUID;

@Data
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@Schema(name = "CreatePaymentResponseDTO", description = "Response object containing details of the created payment")
public class CreatePaymentResponseDTO {

    @Schema(description = "Unique identifier for the payment intent generated by the payment gateway",
            example = "pi_1JN3zd2eZvKYlo2CvZJZ1234", required = true)
    private String paymentIntentId;

    @Schema(description = "Unique correlation ID for tracking the payment request",
            example = "d290f1ee-6c54-4b01-90e6-d701748f0851", required = true)
    private UUID correlationId;
}